### ISSUE TITLE
No empty line before last }

### ISSUE THREAD

**Issue by xtaixe** [palantir/palantir-java-format#831] opened 2023-01-18 17:13 UTC
## What happened?

Hi. Is this intentional?

```
public interface MyClass {

    void myMethod();
}
```

For me it looks really bad (specially for short interfaces and classes, but I would change it in all cases for consistency).

## What did you want to happen?

My preference would be:

```
public interface MyClass {

    void myMethod();

}
```

but this also looks better:

```
public interface MyClass {
    void myMethod();
}
```

Thanks.

**Comment by fawind** [comment] 2023-01-18 17:38
Hey! Yes, this is currently intended behavior. The formatter is not super strict here but requires a single empty line above all interface methods with the exception of the very first method which can also come directly after the interface declaration (without an additional new line). Based on that, both these examples are validly formatted cases and it's currently up to the code author to decide:

```java
public interface MyClass {

    void myMethod();
}
```

```java
public interface MyClass {
    void myMethod();
}
```

I think I tend to agree with your argument that it would be good to enforce one of these styles for consistency. But I think you might get very different opinions on what style this should be.

**Comment by fawind** [comment] 2023-01-18 17:47
Hey! Yes, this is currently intended behavior. No newline before the closing `}`-bracket is a general rule that is applied to all classes and interfaces (and also to methods, for-loops, if-statement, ...). Basically everywhere the rule holds that there shouldn't be trailing empty newlines. Looking at an example with more methods, it might look more reasonable to you:

```java
interface MyClass {

    void myMethodA();

    void myMethodB();

    void myMethodC();
}
```

Based on that, I think it's the consistent behavior to not allow an empty newline before the closing `}`-bracket even for cases with just a single method.

Note that the same doesn't hold for a leading newline after opening a new block (i.e. after an opening `{`-bracket). There, you have the choice between leaving a single empty newline or omitting it. I.e. both these examples are validly formatted:

```java
public interface MyClass {
    void myMethod();
}
```

```java
public interface MyClass {

    void myMethod();
}
```

**Closed as not planned** 2023-09-20 18:05 UTC
